###
# Author:       Tianze Wang
# Email:        tw19j@fsu.edu
# Modified:     10/29/2023
# Copyright:    Optimal Robotics Lab@ Florida State University
###

title = "MPC Configuration"

[robot]
name = "digit"

[MPC-Params]
foot_x_max = 0.8 #
foot_y_max = 0.4 #
W_com_x_p = 0.0
W_com_x_d = 5000.0
W_com_y_p = 0.0
W_com_y_d = 5000.0
W_foot_ux = 10000.0
W_foot_uy = 10000.0
W_foot_dux = 500.0
W_foot_duy = 500.0
W_obs = 0.0
obs_rad1 = 0.0
obs_rad2 = 0.1
foot_width = 0.12
mpc_rate = 50.0       # mpc update rate
ux_off = 0.02         # mpc input x offset
uy_off = 0.002        # mpc input y offset

