###
# Author:       Tianze Wang
# Email:        tw19j@fsu.edu
# Modified:     10/29/2023
# Copyright:    Optimal Robotics Lab @ Florida State University
###

title = "Robot Configuration"

[robot]
name = "digit"

[PD-Gains]
com_P_gain_x = 35.0       # base position gain
com_P_gain_y = 35.0
com_P_gain_z = 40.0
com_D_gain_x = 5.0
com_D_gain_y = 5.0
com_D_gain_z = 5.0
crt_com_D_gain_x = 0.0 # worth checking
crt_com_D_gain_y = 0.0 # worth checking

com_P_gain_rz = 250.0     # base rotation gain
com_P_gain_ry = 250.0
com_P_gain_rx = 250.0
com_D_gain_rz = 25.0
com_D_gain_ry = 25.0
com_D_gain_rx = 25.0

foot_P_x = 155            # foot gain
foot_P_y = 155
foot_P_z = 252.5
foot_D_x = 10
foot_D_y = 10
foot_D_z = 16

hip_yaw_P = 250
hip_yaw_D = 15

arm_P = 250.0      # arm gain
cp_P  = 1.8        # capture point gains, only for capture point walking
mpc_px = 1.0  # worth checking
mpc_py = 1.0  # worth checking

[QP-Params]
st_foot_W = 1350.0
sw_foot_W = 350.0   # foot z weight
sw_foot_Wx = 1350.0
sw_foot_Wy = 1350.0
com_W = 1050.0
com_Wx = 3050.0
com_Wy = 3050.0
com_Wz = 3550.0
com_Wrz = 1050.0
com_Wry = 1050.0
com_Wrx = 1050.0

com_Wxst = 15550.0     # stepping weights
com_Wyst = 15550.0
com_Wzst = 21350.0
com_Wrzst = 10050.0
com_Wryst = 10050.0
com_Wrxst = 10050.0
force_max = 450.0

mu = 0.6             # friction coefficient
qp_rate = 1000.0     # update frequency of the OSC 
osc_version = 0      # 0 for c++ eigen osqp wrapper, 1 for osqp c implementation

[Walk-Params]
step_time = 0.4
step_height = 0.2
end_pos = -0.08
end_vel = -0.5     # velocity when foot hit ground 
end_acc = -5       # Acceleration when foot hig ground
ds_time = 0.01   # Time duration for double support phase

[Filter]
wd_sz = 25000      # number of the consecutive safety violation to trigger safe controller. Control frequency is 1kHz, so 0.5s safe window

[Start]
init_count = 0.3 # Time to record robot's initial configuration
soft_count = 0.2  # Time to soft start motor torques

[Arm-IK]
z_int = -0.1  # initial height for the arm
z_mag = 0.3  # range of arm motion height
z_prd = 1    # period of arm motion

[Other]
recording = 1.0   # change to 1 if want to record controller data
