# Add table in front of the robot and rotate so the AprilTags are facing the robot.
[world.package.body]
type = "box"
size = [0.2, 0.2, 0.1]
pose = {xyz = [0, 0, 0.05]}
mass = 1.0

[world.obstacle.body]
type = "box"
size = [0.2, 0.2, 0.1]
pose = {xyz = [0, 0, 0.05]}
mass = 1.0

# Add robot to world
[[model-list]]
model = "robot"
pose = {rpyxyz = [0, 0, 0, 0, 0, 1]}

[[model-list]]
model = "package"
pose = {axyd = [0, -1.1, 0.1]}
fixed = true

[[model-list]]
model = "obstacle"
pose = {axyd = [0, 1.1, 0.1]}
fixed = true