[lowlevelapi]
enable = true
# Time in seconds between Low-level API packets before control program
# disables robot
timeout = 0.05
# Port for incoming and outgoing Low-level API communications.
# Change if these settings interfere with any other programs or network
# Traffic on the payload computer. Must match settings in lowlevelapi.c
# (lines 181 and 183). These should not be changed under normal operation
listen-port = 25500
send-port = 25501

[simulator]
# Uncomment this for better visualization, but it will cause some state estimate features to be disabled (e.g. foot contact reporting)
#perfect-state = true

[[model-list]]
model = "robot"
pose = {rpyxyz = [0, 0, 3.14, 0, 0, 1]}

